services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Default RabbitMQ port for message broker
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
     #######################
     #       Zipkin        #
     #######################

  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - "9411:9411"


  banking-api:      
    image: bankingapi:dev
    build:
       context: .
       dockerfile: Banking.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - dapr
    networks:
      - app-network

  dapr:
    image: daprio/dapr:latest
    command: [
      "./daprd",
      "-app-id", "bankingapi",
      "-app-port", "5000",
      "-dapr-http-port", "3500",
      "-components-path", "/components"
    ]
    volumes:
      - ./dapr/components:/components
    depends_on:
      - rabbitmq
    networks:
      - app-network

  # bankingapi:
  #   build:
  #     context: .
  #     dockerfile: Banking.API/Dockerfile
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Development"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - dapr
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
