services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      retries: 5

  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - "9411:9411"

  banking-api:      
    image: bankingapi:dev
    build:
       context: .
       dockerfile: Banking.API/Dockerfile
    environment:
       - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - rabbitmq

  dapr:
    image: daprio/dapr:latest
    command: [
      "./daprd",
      "-app-id", "banking-api",
      "-app-port", "5000",
      "-dapr-http-port", "3500",
      "-components-path", "/components"
    ]
    volumes:
      - ./dapr/components:/components
    depends_on:
      rabbitmq:
         condition: service_healthy
    network_mode: service:banking-api
