apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: withdrawalpubsub
scopes:
  - banking-api
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://guest:guest@rabbitmq:5672"
